--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    id bigint NOT NULL
);


--
-- Name: branches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.branches (
    company_id bigint,
    id bigint NOT NULL,
    city character varying(255),
    direction character varying(255)
);


--
-- Name: branches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    province smallint,
    company_id bigint NOT NULL,
    id bigint NOT NULL,
    client_type character varying(31) NOT NULL,
    address character varying(255),
    associate_name character varying(255),
    associate_phone character varying(255),
    associate_surname character varying(255),
    cuit character varying(255),
    email character varying(255),
    location character varying(255),
    name character varying(255),
    phone character varying(255),
    razon_social character varying(255),
    search_text character varying(255) NOT NULL,
    sort_key character varying(255) NOT NULL,
    surname character varying(255),
    CONSTRAINT clients_client_type_check CHECK (((client_type)::text = ANY ((ARRAY['NATURAL_PERSON'::character varying, 'RAZON_SOCIAL'::character varying])::text[]))),
    CONSTRAINT clients_province_check CHECK (((province >= 0) AND (province <= 22)))
);


--
-- Name: clients_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clients_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: companys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companys (
    id bigint NOT NULL,
    logo_id bigint,
    cuit character varying(255),
    legal_name character varying(255),
    name character varying(255)
);


--
-- Name: companys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imagens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imagens (
    id bigint NOT NULL,
    public_id character varying(255),
    url character varying(255)
);


--
-- Name: imagens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.imagens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: optionals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.optionals (
    money smallint,
    price double precision,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    name character varying(255),
    CONSTRAINT optionals_money_check CHECK (((money >= 0) AND (money <= 1)))
);


--
-- Name: optionals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.optionals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.optionals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    application smallint,
    bonus_percentage double precision NOT NULL,
    deleted boolean NOT NULL,
    percentage double precision,
    id bigint NOT NULL,
    vigente_payments_id bigint,
    description character varying(255),
    CONSTRAINT payment_application_check CHECK (((application >= 0) AND (application <= 2)))
);


--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_types (
    id bigint NOT NULL,
    id_company bigint,
    imagen_id bigint,
    name character varying(255)
);


--
-- Name: product_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    freight double precision,
    list_price double precision,
    porcent integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    id_type bigint,
    provider_id bigint NOT NULL,
    description character varying(500),
    iva character varying(255),
    money character varying(255),
    normalize_value character varying(255),
    value character varying(255),
    CONSTRAINT products_iva_check CHECK (((iva)::text = ANY ((ARRAY['GENERAL'::character varying, 'REDUCIDA'::character varying])::text[]))),
    CONSTRAINT products_money_check CHECK (((money)::text = ANY ((ARRAY['ARS'::character varying, 'USD'::character varying])::text[])))
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    company_id bigint NOT NULL,
    id bigint NOT NULL,
    traveler_id bigint,
    cuit character varying(255),
    legal_name character varying(255),
    phone_number character varying(255),
    trade_name character varying(255),
    price_list bigint[]
);


--
-- Name: providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travelers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travelers (
    id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL
);


--
-- Name: travelers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travelers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travelers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    role smallint,
    branch_id bigint,
    company_id bigint,
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    surname character varying(255),
    CONSTRAINT users_role_check CHECK (((role >= 0) AND (role <= 3)))
);


--
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: vigent_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vigent_payments (
    id bigint NOT NULL,
    provider_id bigint,
    update_at timestamp(6) without time zone,
    name_list character varying(255)
);


--
-- Name: vigent_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vigent_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vigent_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: branches branches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (id);


--
-- Name: clients clients_cuit_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_cuit_key UNIQUE (cuit);


--
-- Name: clients clients_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_email_key UNIQUE (email);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: companys companys_logo_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companys
    ADD CONSTRAINT companys_logo_id_key UNIQUE (logo_id);


--
-- Name: companys companys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companys
    ADD CONSTRAINT companys_pkey PRIMARY KEY (id);


--
-- Name: imagens imagens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imagens
    ADD CONSTRAINT imagens_pkey PRIMARY KEY (id);


--
-- Name: optionals optionals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.optionals
    ADD CONSTRAINT optionals_pkey PRIMARY KEY (id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: product_types product_types_imagen_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_types
    ADD CONSTRAINT product_types_imagen_id_key UNIQUE (imagen_id);


--
-- Name: product_types product_types_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_types
    ADD CONSTRAINT product_types_name_key UNIQUE (name);


--
-- Name: product_types product_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_types
    ADD CONSTRAINT product_types_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: providers providers_cuit_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_cuit_key UNIQUE (cuit);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- Name: providers providers_traveler_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_traveler_id_key UNIQUE (traveler_id);


--
-- Name: travelers travelers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travelers
    ADD CONSTRAINT travelers_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vigent_payments vigent_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vigent_payments
    ADD CONSTRAINT vigent_payments_pkey PRIMARY KEY (id);


--
-- Name: vigent_payments vigent_payments_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vigent_payments
    ADD CONSTRAINT vigent_payments_provider_id_key UNIQUE (provider_id);


--
-- Name: product_types fk2b6e75dviyi6l65aew9i9h73a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_types
    ADD CONSTRAINT fk2b6e75dviyi6l65aew9i9h73a FOREIGN KEY (imagen_id) REFERENCES public.imagens(id);


--
-- Name: branches fk4cf4qcp65vgx6g6w3h616fq4a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT fk4cf4qcp65vgx6g6w3h616fq4a FOREIGN KEY (company_id) REFERENCES public.companys(id);


--
-- Name: users fk9o70sp9ku40077y38fk4wieyk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk9o70sp9ku40077y38fk4wieyk FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: admins fkanhsicqm3lc8ya77tr7r0je18; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT fkanhsicqm3lc8ya77tr7r0je18 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: vigent_payments fkfj4udli0ejecvqe5do5nx19h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vigent_payments
    ADD CONSTRAINT fkfj4udli0ejecvqe5do5nx19h FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: providers fkkdvdv3ja0unlk9d9y26fu95a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT fkkdvdv3ja0unlk9d9y26fu95a FOREIGN KEY (traveler_id) REFERENCES public.travelers(id);


--
-- Name: optionals fkkimkimykqb9yajts67r6h3yu9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.optionals
    ADD CONSTRAINT fkkimkimykqb9yajts67r6h3yu9 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: users fkovlkx4qpv57fomaj2ihtdgi2s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkovlkx4qpv57fomaj2ihtdgi2s FOREIGN KEY (company_id) REFERENCES public.companys(id);


--
-- Name: companys fkrt5xb5sxpl29i94lhuul0gyu0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companys
    ADD CONSTRAINT fkrt5xb5sxpl29i94lhuul0gyu0 FOREIGN KEY (logo_id) REFERENCES public.imagens(id);


--
-- Name: payment fksoc9utorn9vgkyd42ywe22rsq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fksoc9utorn9vgkyd42ywe22rsq FOREIGN KEY (vigente_payments_id) REFERENCES public.vigent_payments(id);


--
-- PostgreSQL database dump complete
--

