spring.config.import=optional:file:.env[.properties]

spring.application.name=agro
server.port=${PORT:8080}

# Datasource (en la app podés usar el host pooled de Neon)
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.profiles.active=${SPRING.PROFILE}

# CORS
app.cors.allowed-origins=${CORS.ALLOWED}

# JPA / Hibernate (el esquema lo maneja Flyway)
spring.jpa.hibernate.ddl-auto=${SPRING.DLL:none}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=${FLYWAY_CLEAN_DISABLED:true}

spring.flyway.url=${FLYWAY_URL:${spring.datasource.url}}
spring.flyway.user=${FLYWAY_USER:${spring.datasource.username}}
spring.flyway.password=${FLYWAY_PASSWORD:${spring.datasource.password}}

# Arranque más rápido en Render free
spring.main.lazy-initialization=true
spring.jmx.enabled=false

# Health check para Render
management.endpoints.web.exposure.include=health

# Spring security
spring.security.user.name=user
logging.level.root=INFO
logging.level.org.springframework.security=INFO

# Token sign
jwt.secret=${JWT.SECRET}

# Resend
resend.api-key=${RESEND_API_KEY}

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Cloudinary
cloudinary.url=${CLOUDINARY_URL}